### ISSUE TITLE
Parameter to Tokenizer should be two letter

### ISSUE THREAD

**Issue by avinashpaul** [irshadbhat/polyglot-tokenizer#2]
tk =Tokenizer(lang='eng', smt=True)

prefixes in of files in DATA  are two letters, nonbreaking_prefixes.ca

**Comment by irshadbhat** [comment]
Oh yes. Actually I recently added tokenization support for almost all major languages of the world (60+) and thus switched from ISO 3 letter language code to ISO 2 letter language code but forgot to update readme. 

Also the reason I changed the repository name from `indic-tokenizer` to `polyglot-tokenizer`.

I have updated the README.

Closing issue. In case there is any other doubt regarding the issue, feel free to reopen.
