### ISSUE TITLE
Gujarati Tokenizer problem

### ISSUE THREAD

**Issue by simonefrancia** [irshadbhat/polyglot-tokenizer#4]
Hello, 
I am trying to use gujarati Tokenizer, as described in README. 

```from __future__ import unicode_literals
from polyglot_tokenizer import Tokenizer
tk = Tokenizer(lang='gu', smt=True)
text = "થમિકશાળાપંચાયતઘરઆંગણવાડીતેમજદૂધનીડેરીજેવીસવલતોપ્રાપ્યથયેલીછે"
tk.tokenize(text)
```
The result seems not to token the input string.

```[u'\u0aa5\u0aae\u0abf\u0a95\u0ab6\u0abe\u0ab3\u0abe\u0aaa\u0a82\u0a9a\u0abe\u0aaf\u0aa4\u0a98\u0ab0\u0a86\u0a82\u0a97\u0aa3\u0ab5\u0abe\u0aa1\u0ac0\u0aa4\u0ac7\u0aae\u0a9c\u0aa6\u0ac2\u0aa7\u0aa8\u0ac0\u0aa1\u0ac7\u0ab0\u0ac0\u0a9c\u0ac7\u0ab5\u0ac0\u0ab8\u0ab5\u0ab2\u0aa4\u0acb\u0aaa\u0acd\u0ab0\u0abe\u0aaa\u0acd\u0aaf\u0aa5\u0aaf\u0ac7\u0ab2\u0ac0\u0a9b\u0ac7']```

Thanks

**Comment by irshadbhat** [comment]
There is nothing wrong with the output. Tokenizer returns a list of tokens separating punctuations, special characters etc. The input string is a single token, so the output lists the whole string as one token. 

```
print tk.tokenize(text)[0]
થમિકશાળાપંચાયતઘરઆંગણવાડીતેમજદૂધનીડેરીજેવીસવલતોપ્રાપ્યથયેલીછે
```

This will give you a better idea what is expected from the tokenizer.
```
from polyglot_tokenizer import Tokenizer
tk = Tokenizer(lang='gu', smt=True)
text = "સ્થાનિક શાસન સામે લડવા સત્યાગ્રહીઓ તૈયાર થયા. ઠેર-ઠેર સભા સરઘસ યોજાયા."
for wd in text.split():
    print wd

સ્થાનિક
શાસન
સામે
લડવા
સત્યાગ્રહીઓ
તૈયાર
થયા.
ઠેર-ઠેર
સભા
સરઘસ
યોજાયા.
for wd in tk.tokenize(text):
    print wd

સ્થાનિક
શાસન
સામે
લડવા
સત્યાગ્રહીઓ
તૈયાર
થયા
.
ઠેર-ઠેર
સભા
સરઘસ
યોજાયા
.
```

**Comment by simonefrancia** [comment]
Thanks for support!
