### ISSUE TITLE
Malaya Tokenizer error

### ISSUE THREAD

**Issue by simonefrancia** [irshadbhat/polyglot-tokenizer#5]
Hi,
 
Trying to use Malaya tokenizer, an error occurs. Going into polyglot_tokenizer/data, that file doesn't exist. 

```IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/indictrans/polyglot_tokenizer/data/nonbreaking_prefixes.ma```

Where can I find this file? Thanks

**Comment by irshadbhat** [comment]
There is no official support for Malaya. But English tokenizer might work for it.

**Comment by simonefrancia** [comment]
Do you think it's better an Indian Tokenizer like Hindi, instead of Eng?
Thanks
